name: CICDJosueAuquillaa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Imprimir mensaje de despliegue
      run: echo "Desplegando cambios..."

    - name: Empujar cambios al repositorio remoto
      run: git push origin main
